
name: Publish-Wasm

on:
  workflow_dispatch:
  push:
    tags:
      - ducklab-wasm/v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - working-directory: ./wasm
        run: |
          npm i -g pnpm
          pnpm install
          pnpm run build

      # - name: Deploy to Netlify
      #   uses: nwtgck/actions-netlify@v3.0
      #   with:
      #     publish-dir: './wasm/dist'
      #     production-branch: main
      #   env:
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.DUCKLAB_NETLIFY_PAT }}
      #     NETLIFY_SITE_ID: ${{ secrets.DUCKLAB_NETLIFY_SITE_ID }}
      #   timeout-minutes: 1
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: ./wasm/dist
          retention-days: 1

  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    
